"""empty message

Revision ID: 92e2a3f23e3b
Revises: 
Create Date: 2019-10-22 10:31:13.239847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e2a3f23e3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_desc', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('chart1', sa.LargeBinary(), nullable=True),
    sa.Column('chart1_caption', sa.String(), nullable=True),
    sa.Column('chart2', sa.LargeBinary(), nullable=True),
    sa.Column('chart2_caption', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_title'), 'article', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_article_title'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
